<?php

namespace app\admin\command;

use app\common\library\Menu;
use badou\TableManager;
use think\console\Command;
use think\console\Input;
use think\console\input\Option;
use think\console\Output;
use think\facade\Db;

class Crud extends Command
{
    protected $stubList = [];
    protected $fieldMaxLen = 0;
    protected $internalKeywords = [
        'abstract', 'and', 'array', 'as', 'break', 'callable', 'case', 'catch', 'class', 'clone', 'const',
        'continue', 'declare', 'default', 'die', 'do', 'echo', 'else', 'elseif', 'empty', 'enddeclare',
        'endfor', 'endforeach', 'endif', 'endswitch', 'endwhile', 'eval', 'exit', 'extends', 'final',
        'for', 'foreach', 'function', 'global', 'goto', 'if', 'implements', 'include', 'include_once',
        'instanceof', 'insteadof', 'interface', 'isset', 'list', 'namespace', 'new', 'or', 'print',
        'private', 'protected', 'public', 'require', 'require_once', 'return', 'static', 'switch',
        'throw', 'trait', 'try', 'unset', 'use', 'var', 'while', 'xor',
    ];
    protected $systemTables = [
        'admin', 'admin_log', 'admin_rule', 'admin_group', 'admin_group_access',
        'config', 'attachment', 'user', 'user_group', 'user_rule', 'user_level', 'user_token',
    ];
    protected $enumRadioSuffix = ['data', 'state', 'status'];
    protected $setCheckboxSuffix = ['data', 'state', 'status'];
    protected $intDateSuffix = ['time'];
    protected $switchSuffix = ['switch'];
    protected $editorSuffix = ['content'];
    protected $selectpageSuffix = ['_id', '_ids'];
    protected $selectpagesSuffix = ['_ids'];
    protected $imageField = ['image', 'images', 'avatar', 'avatars', 'pic', 'logo', 'cover', 'thumb'];
    protected $fileField = ['file', 'files'];
    protected $ignoreFields = [];
    protected $sortField = 'weigh';
    protected $createTimeField = 'create_time';
    protected $updateTimeField = 'update_time';
    protected $deleteTimeField = 'delete_time';
    protected $editorClass = 'editor';
    protected $fieldFormatterSuffix = [
        'status' => ['type' => ['varchar', 'enum'], 'name' => 'status'],
        'image' => 'image',
        'images' => 'image',
        'avatar' => 'image',
        'pic' => 'image',
        'logo' => 'image',
        'cover' => 'image',
        'thumb' => 'image',
        'file' => 'file',
        'files' => 'file',
        'switch' => 'switch',
        'time' => ['type' => ['int', 'bigint', 'timestamp'], 'name' => 'datetime'],
    ];

    protected function configure()
    {
        $this->setName('crud')
            ->addOption('table', 't', Option::VALUE_REQUIRED, 'table name without prefix', null)
            ->addOption('controller', 'c', Option::VALUE_OPTIONAL, 'controller name', null)
            ->addOption('model', 'm', Option::VALUE_OPTIONAL, 'model name', null)
            ->addOption('fields', 'i', Option::VALUE_OPTIONAL, 'model visible fields', null)
            ->addOption('force', 'f', Option::VALUE_OPTIONAL, 'force override or force delete', null)
            ->addOption('local', 'l', Option::VALUE_OPTIONAL, 'local model', 1)
            ->addOption('relation', 'r', Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'relation table name without prefix', null)
            ->addOption('relationmodel', 'e', Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'relation model name', null)
            ->addOption('relationforeignkey', 'k', Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'relation foreign key', null)
            ->addOption('relationprimarykey', 'p', Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'relation primary key', null)
            ->addOption('relationfields', 's', Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'relation table fields', null)
            ->addOption('relationmode', 'o', Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'relation mode,hasone/belongsto/hasmany', null)
            ->addOption('relationcontroller', 'w', Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'relation controller', null)
            ->addOption('delete', 'd', Option::VALUE_OPTIONAL, 'delete files generated by CRUD', null)
            ->addOption('menu', 'u', Option::VALUE_OPTIONAL, 'create menu, pass a title to override', null)
            ->addOption('ignorefields', null, Option::VALUE_OPTIONAL | Option::VALUE_IS_ARRAY, 'ignore fields', null)
            ->addOption('sortfield', null, Option::VALUE_OPTIONAL, 'sort field', null)
            ->setDescription('Build CRUD controller and model from table');
    }

    protected function execute(Input $input, Output $output)
    {
        $table = (string)$input->getOption('table');
        if ($table === '') {
            throw new \InvalidArgumentException('table name can\'t empty');
        }
        $prefix = $this->prefix();
        $table = stripos($table, $prefix) === 0 ? substr($table, strlen($prefix)) : $table;
        if (in_array($table, $this->systemTables, true)) {
            throw new \InvalidArgumentException('system table can\'t be crud');
        }
        if ($input->getOption('ignorefields')) {
            $this->ignoreFields = $input->getOption('ignorefields');
        }
        if ($input->getOption('sortfield')) {
            $this->sortField = (string)$input->getOption('sortfield');
        }

        $controller = $input->getOption('controller');
        $model = $input->getOption('model') ?: $controller;
        $force = $this->truthy($input->getOption('force'));
        $delete = $this->truthy($input->getOption('delete'));
        $local = (int)$input->getOption('local') !== 0;
        $menuOption = $input->getOption('menu');
        $withMenu = $menuOption !== null && $menuOption !== false && $menuOption !== '';

        [$controllerNamespace, $controllerName, $controllerFile, $controllerArr] = $this->parseName('controller', $controller, $table, 'admin');
        [$modelNamespace, $modelName, $modelFile, $modelArr] = $this->parseName('model', $model, $table, $local ? 'admin' : 'common');
        [$validateNamespace, $validateName, $validateFile] = $this->parseName('validate', $model, $table, $local ? 'admin' : 'common');
        $controllerUrl = strtolower(implode('.', $controllerArr));
        $viewDir = root_path() . 'app/admin/view/' . str_replace('.', '/', $controllerUrl) . '/';
        $langFile = root_path() . 'app/admin/lang/zh-cn/' . str_replace('.', '/', $controllerUrl) . '.php';
        $files = [
            $controllerFile,
            $modelFile,
            $validateFile,
            $viewDir . 'index.html',
            $viewDir . 'add.html',
            $viewDir . 'edit.html',
            $langFile,
        ];

        if ($delete) {
            foreach ($files as $file) {
                if (is_file($file)) {
                    unlink($file);
                    $output->writeln($file);
                }
            }
            if ($withMenu) {
                Menu::delete($controllerUrl);
            }
            $output->writeln('<info>Delete Successed</info>');
            return;
        }

        if ((is_file($controllerFile) || is_file($modelFile) || is_file($validateFile)) && !$force) {
            throw new \RuntimeException('控制器已存在，如需重新生成请勾选强制覆盖');
        }

        $fullTable = TableManager::tableName($table, true);
        $columns = TableManager::getTableColumns($table);
        if (!$columns) {
            throw new \RuntimeException('table not found');
        }
        $columnList = array_values($columns);
        $fieldArr = array_keys($columns);
        $this->detectTimeFields($fieldArr);
        $priKey = '';
        foreach ($columnList as $column) {
            if (($column['COLUMN_KEY'] ?? '') === 'PRI') {
                $priKey = $column['COLUMN_NAME'];
                break;
            }
        }
        if ($priKey === '') {
            throw new \RuntimeException('Primary key not found!');
        }

        $relations = $this->relations($input, $table, $prefix, $fieldArr, $priKey, $local ? 'admin' : 'common');
        $tableComment = $this->tableComment($fullTable);
        $menuTitle = is_string($menuOption) && !in_array($menuOption, ['1', 'true', 'yes'], true) ? $menuOption : $tableComment;

        $addList = [];
        $editList = [];
        $javascriptList = ["                    { type: \"checkbox\" }"];
        $langList = [];
        $getEnumArr = [];
        $getAttrArr = [];
        $setAttrArr = [];
        $appendAttrList = [];
        $controllerAssignList = [];
        $order = in_array($this->sortField, $fieldArr, true) ? $this->sortField : $priKey;
        $reserved = ['admin_id', $this->createTimeField, $this->updateTimeField, $this->deleteTimeField, 'createtime', 'updatetime', 'deletetime'];
        $visible = $input->getOption('fields') ? explode(',', (string)$input->getOption('fields')) : [];

        foreach ($columnList as $column) {
            $field = $column['COLUMN_NAME'];
            $itemArr = $this->items($column);
            if ($itemArr && !in_array($column['DATA_TYPE'], ['enum', 'set'], true)) {
                $column['DATA_TYPE'] = 'enum';
            }
            if (($column['COLUMN_COMMENT'] ?? '') !== '') {
                $langList[] = $this->langItem($field, $column['COLUMN_COMMENT']);
            }
            $inputType = '';
            if ($column['COLUMN_KEY'] !== 'PRI' && !in_array($field, $reserved, true) && !in_array($field, $this->ignoreFields, true)) {
                $inputType = $this->fieldType($column);
                [$addElement, $editElement] = $this->formElements($field, $column, $inputType, $itemArr, $relations, $prefix, $table, $getEnumArr, $getAttrArr, $setAttrArr, $appendAttrList, $controllerAssignList);
                $addList[] = $this->formGroup($field, $addElement);
                $editList[] = $this->formGroup($field, $editElement);
            }
            if ($column['DATA_TYPE'] !== 'text' && (!$visible || in_array($field, $visible, true) || $field === $priKey)) {
                $javascriptList[] = $this->jsColumn($field, $column, $inputType, $itemArr);
            }
        }

        $javascriptList[] = '                    { title: __("Operate"), width: 180, templet: bdTable.api.formatter.operate }';
        $relationWith = '';
        $relationMethods = '';
        $controllerIndex = '';
        if ($relations) {
            $with = [];
            $methods = [];
            foreach ($relations as $relation) {
                $methods[] = $this->stub($relation['relationMode'] === 'hasMany' ? 'mixins/modelrelationmethod-hasmany' : 'mixins/modelrelationmethod', $relation);
                if ($relation['relationMode'] !== 'hasMany') {
                    $with[] = $relation['relationMethod'];
                }
            }
            $relationMethods = implode("\n", $methods);
            if ($with) {
                $relationWith = "->with(['" . implode("','", $with) . "'])";
                $controllerIndex = $this->stub('controllerindex', [
                    'relationSearch' => 'true',
                    'relationWithList' => $relationWith,
                ]);
            }
        }

        $data = [
            'controllerNamespace' => $controllerNamespace,
            'modelNamespace' => $modelNamespace,
            'validateNamespace' => $validateNamespace,
            'controllerName' => $controllerName,
            'modelName' => $modelName,
            'validateName' => $validateName,
            'controllerAssignList' => implode("\n", $controllerAssignList),
            'controllerIndex' => $controllerIndex,
            'controllerUrl' => $controllerUrl,
            'tableComment' => $tableComment,
            'table' => $table,
            'tableId' => str_replace('.', '_', $controllerUrl),
            'pk' => $priKey,
            'order' => $order,
            'modelTableType' => 'name',
            'modelTableTypeName' => $table,
            'modelConnection' => '',
            'modelAutoWriteTimestamp' => in_array($this->createTimeField, $fieldArr, true) || in_array($this->updateTimeField, $fieldArr, true) ? 'true' : 'false',
            'modelTypeList' => $this->modelTypeList($columnList),
            'createTime' => in_array($this->createTimeField, $fieldArr, true) ? "'{$this->createTimeField}'" : 'false',
            'updateTime' => in_array($this->updateTimeField, $fieldArr, true) ? "'{$this->updateTimeField}'" : 'false',
            'deleteTime' => in_array($this->deleteTimeField, $fieldArr, true) ? "'{$this->deleteTimeField}'" : 'false',
            'softDeleteClassPath' => in_array($this->deleteTimeField, $fieldArr, true) ? 'use think\\model\\concern\\SoftDelete;' : '',
            'softDelete' => in_array($this->deleteTimeField, $fieldArr, true) ? '    use SoftDelete;' : '',
            'appendAttrList' => implode(",\n", $appendAttrList),
            'getEnumList' => implode("\n\n", $getEnumArr),
            'getAttrList' => implode("\n\n", $getAttrArr),
            'setAttrList' => implode("\n\n", $setAttrArr),
            'relationMethodList' => $relationMethods,
            'modelInit' => $order !== $priKey ? $this->stub('mixins/modelinit', ['order' => $order]) : '',
            'addList' => implode("\n", $addList),
            'editList' => implode("\n", $editList),
            'javascriptList' => implode(",\n", $javascriptList),
            'langList' => implode(",\n", array_filter($langList)),
            'importHtml' => '',
            'relationSearch' => $relations ? 'true' : 'false',
            'relationWithList' => $relationWith,
        ];

        $this->write('controller', $data, $controllerFile);
        $this->write('model', $data, $modelFile);
        $this->write('validate', $data, $validateFile);
        $this->write('index', $data, $viewDir . 'index.html');
        $this->write('add', $data, $viewDir . 'add.html');
        $this->write('edit', $data, $viewDir . 'edit.html');
        $this->write('lang', $data, $langFile);
        foreach ($relations as $relation) {
            if (!is_file($relation['relationFile'])) {
                $this->write('relationmodel', $relation, $relation['relationFile']);
            }
        }
        if ($withMenu) {
            $menu = [[
                'name' => $controllerUrl,
                'title' => $menuTitle,
                'icon' => 'fa fa-list',
                'ismenu' => 1,
                'type' => '1',
                'sublist' => [
                    ['name' => $controllerUrl . '/index', 'title' => '查看', 'ismenu' => 0, 'type' => '2'],
                    ['name' => $controllerUrl . '/add', 'title' => '添加', 'ismenu' => 0, 'type' => '2'],
                    ['name' => $controllerUrl . '/edit', 'title' => '编辑', 'ismenu' => 0, 'type' => '2'],
                    ['name' => $controllerUrl . '/del', 'title' => '删除', 'ismenu' => 0, 'type' => '2'],
                    ['name' => $controllerUrl . '/multi', 'title' => '批量更新', 'ismenu' => 0, 'type' => '2'],
                ],
            ]];
            $exists = Db::name('admin_rule')->where('name', $controllerUrl)->find();
            if ($exists) {
                Menu::upgrade($controllerUrl, $menu);
            } else {
                Menu::create($menu);
            }
        }
        $output->writeln('<info>Build Successed</info>');
    }

    protected function formElements($field, $column, $inputType, $itemArr, $relations, $prefix, $table, &$getEnumArr, &$getAttrArr, &$setAttrArr, &$appendAttrList, &$controllerAssignList): array
    {
        $name = "row[{$field}]";
        $default = $column['COLUMN_DEFAULT'];
        $default = ($default === null || $default === 'NULL') ? '' : $default;
        $required = ($column['IS_NULLABLE'] ?? '') === 'NO' ? ' lay-verify="required"' : '';
        $addValue = htmlspecialchars((string)$default, ENT_QUOTES);
        $editValue = "{\$row.{$field}|default=''|htmlentities}";

        if (in_array($inputType, ['select', 'radio', 'checkbox'], true)) {
            $this->enumMethods($getEnumArr, $controllerAssignList, $field, $itemArr, $inputType);
            $this->attrMethods($getAttrArr, $setAttrArr, $appendAttrList, $field, $inputType);
            $fieldName = $inputType === 'checkbox' ? $name . '[]' : $name;
            $selected = $inputType === 'checkbox' || $inputType === 'radio' ? $default : $default;
            $editSelected = "\$row.{$field}";
            $add = $this->stub('html/' . $inputType, ['field' => $field, 'fieldName' => $fieldName, 'fieldList' => $this->listName($field), 'attrStr' => trim($required), 'selectedValue' => $selected]);
            $edit = $this->stub('html/' . $inputType, ['field' => $field, 'fieldName' => $fieldName, 'fieldList' => $this->listName($field), 'attrStr' => trim($required), 'selectedValue' => $editSelected]);
            return [$add, $edit];
        }
        if ($inputType === 'switch') {
            $yes = ($default === '0' || $default === 'N') ? ($default === '0' ? '1' : 'Y') : ($default !== '' ? $default : '1');
            $no = $yes === '1' ? '0' : ($yes === 'Y' ? 'N' : '0');
            $add = $this->stub('html/switch', ['fieldName' => $name, 'fieldYes' => $yes, 'fieldNo' => $no, 'fieldValue' => $yes]);
            $edit = $this->stub('html/switch', ['fieldName' => $name, 'fieldYes' => $yes, 'fieldNo' => $no, 'fieldValue' => "\$row.{$field}"]);
            return [$add, $edit];
        }
        if ($inputType === 'datetime') {
            $class = 'layui-input laydate';
            return [
                "<input type=\"text\" name=\"{$name}\" value=\"{$addValue}\" class=\"{$class}\" autocomplete=\"off\"{$required}>",
                "<input type=\"text\" name=\"{$name}\" value=\"{$editValue}\" class=\"{$class}\" autocomplete=\"off\"{$required}>",
            ];
        }
        if ($inputType === 'textarea') {
            $class = 'layui-textarea' . ($this->matchSuffix($field, $this->editorSuffix) ? ' ' . $this->editorClass : '');
            return [
                "<textarea name=\"{$name}\" class=\"{$class}\"{$required}></textarea>",
                "<textarea name=\"{$name}\" class=\"{$class}\"{$required}>{$editValue}</textarea>",
            ];
        }

        $relation = $this->selectpage($field, $relations, $prefix);
        if ($relation) {
            $multiple = $this->matchSuffix($field, $this->selectpagesSuffix) ? ' data-multiple="true"' : '';
            $box = "<input type=\"hidden\" id=\"c-{$field}\" name=\"{$name}\" value=\"%s\">\n            <div class=\"remoteSelect\" data-input-id=\"c-{$field}\" data-field=\"{$relation['field']}\" data-primary-key=\"{$relation['pk']}\" data-source=\"{$relation['controller']}/selectpage\"{$multiple}></div>";
            return [sprintf($box, $addValue), sprintf($box, $editValue)];
        }
        if ($this->matchSuffix($field, array_merge($this->imageField, $this->fileField))) {
            $upload = "<input type=\"text\" id=\"c-{$field}\" name=\"{$name}\" value=\"%s\" class=\"layui-input\"{$required}>\n            <div class=\"layui-input-suffix\" style=\"width:30%%\"><button type=\"button\" data-input-id=\"c-{$field}\" data-preview-id=\"p-{$field}\" class=\"layui-btn btn-bdupload\"><i class=\"fa fa-upload\"></i> 上传</button><button type=\"button\" data-input-id=\"c-{$field}\" class=\"layui-btn layui-bg-green btn-bdchoose\"><i class=\"fa fa-list\"></i> 选择</button></div>\n            <div class=\"layui-upload-list\" id=\"p-{$field}\"></div>";
            return [sprintf($upload, $addValue), sprintf($upload, $editValue)];
        }
        $type = $inputType === 'number' ? 'number' : 'text';
        return [
            "<input type=\"{$type}\" name=\"{$name}\" value=\"{$addValue}\" class=\"layui-input\" autocomplete=\"off\"{$required}>",
            "<input type=\"{$type}\" name=\"{$name}\" value=\"{$editValue}\" class=\"layui-input\" autocomplete=\"off\"{$required}>",
        ];
    }

    protected function selectpage(string $field, array $relations, string $prefix): ?array
    {
        if (!$this->matchSuffix($field, $this->selectpageSuffix)) {
            return null;
        }
        $table = substr($field, 0, (int)strripos($field, '_'));
        foreach ($relations as $relation) {
            if ($relation['relationForeignKey'] === $field) {
                $name = $relation['relationTableName'];
                $table = stripos($name, $prefix) === 0 ? substr($name, strlen($prefix)) : $name;
                break;
            }
        }
        if (!TableManager::getTableColumns($table)) {
            return null;
        }
        $columns = TableManager::getTableColumns($table);
        $show = 'id';
        foreach (['nickname', 'title', 'name'] as $candidate) {
            if (isset($columns[$candidate])) {
                $show = $candidate;
                break;
            }
        }
        $pk = 'id';
        foreach ($columns as $name => $column) {
            if (($column['COLUMN_KEY'] ?? '') === 'PRI') {
                $pk = $name;
                break;
            }
        }
        return ['field' => $show, 'pk' => $pk, 'controller' => $this->controllerUrlOfTable($table)];
    }

    protected function controllerUrlOfTable(string $table): string
    {
        $special = [
            'user' => 'user.user',
            'admin' => 'auth.admin',
        ];
        if (isset($special[$table])) {
            return $special[$table];
        }
        $parts = explode('_', $table);
        $candidates = [];
        if (count($parts) > 1) {
            $module = array_shift($parts);
            $candidates[] = $module . '.' . $this->snake(implode('_', $parts));
            $candidates[] = $module . '.' . $module;
        }
        $candidates[] = $this->snake($table) . '.' . $this->snake($table);
        $candidates[] = $this->snake($table);
        foreach ($candidates as $candidate) {
            $file = root_path() . 'app/admin/controller/' . str_replace('.', '/', $candidate) . '.php';
            if (is_file($file)) {
                return strtolower($candidate);
            }
        }
        return strtolower($candidates[0]);
    }

    protected function snake(string $value): string
    {
        $value = preg_replace('/(?<!^)[A-Z]/', '_$0', $value);
        return strtolower(str_replace('-', '_', (string)$value));
    }

    protected function relations(Input $input, string $table, string $prefix, array $fieldArr, string $priKey, string $module): array
    {
        $relation = $input->getOption('relation') ?: [];
        $result = [];
        foreach ($relation as $index => $relationTable) {
            $relationName = stripos($relationTable, $prefix) === 0 ? substr($relationTable, strlen($prefix)) : $relationTable;
            $columns = TableManager::getTableColumns($relationName);
            if (!$columns) {
                throw new \RuntimeException('relation table not found');
            }
            $mode = $input->getOption('relationmode')[$index] ?? 'belongsto';
            $foreign = $input->getOption('relationforeignkey')[$index] ?? ($mode === 'belongsto' ? $relationName . '_id' : $table . '_id');
            $primary = $input->getOption('relationprimarykey')[$index] ?? $priKey;
            $modelOption = $input->getOption('relationmodel')[$index] ?? '';
            [$namespace, $name, $file] = $this->parseName('model', $modelOption, $relationName, $module);
            $result[] = [
                'relationName' => $name,
                'relationNamespace' => $namespace,
                'relationFile' => $file,
                'relationTableName' => TableManager::tableName($relationName, true),
                'relationTableType' => 'name',
                'relationTableTypeName' => $relationName,
                'relationMode' => $mode === 'hasmany' ? 'hasMany' : ($mode === 'hasone' ? 'hasOne' : 'belongsTo'),
                'relationMethod' => lcfirst($name),
                'relationForeignKey' => $foreign,
                'relationPrimaryKey' => $primary,
                'relationClassName' => '\\' . $namespace . '\\' . $name,
                'relationFields' => isset($input->getOption('relationfields')[$index]) ? explode(',', $input->getOption('relationfields')[$index]) : [],
                'modelNamespace' => $namespace,
            ];
            unset($fieldArr);
        }
        return $result;
    }

    protected function jsColumn(string $field, array $column, string $inputType, array $itemArr): string
    {
        $lang = $this->langKey($field);
        $parts = ["field: \"{$field}\"", "title: __('{$lang}')"];
        if (($column['COLUMN_KEY'] ?? '') === 'PRI') {
            $parts[] = 'width: 80';
            $parts[] = 'sort: true';
        }
        $formatter = '';
        foreach ($this->fieldFormatterSuffix as $suffix => $value) {
            if (preg_match("/{$suffix}$/i", $field)) {
                if (is_array($value)) {
                    if (in_array($column['DATA_TYPE'], $value['type'], true)) {
                        $formatter = $value['name'];
                    }
                } else {
                    $formatter = $value;
                }
                break;
            }
        }
        if ($itemArr && !$formatter) {
            $formatter = 'status';
            $search = [];
            foreach ($itemArr as $key => $value) {
                $search[$key] = "__('" . $this->langKey($value) . "')";
            }
            $json = json_encode($search, JSON_UNESCAPED_UNICODE);
            $json = str_replace(['":"', '"}', ')","'], ['":', '}', '),"'], $json);
            $parts[] = 'searchList: ' . $json;
        }
        if (in_array($column['DATA_TYPE'], ['varchar', 'char', 'text'], true) && !$this->matchSuffix($field, array_merge($this->imageField, $this->fileField))) {
            $parts[] = "operate: 'LIKE'";
        }
        if ($this->matchSuffix($field, array_merge($this->imageField, $this->fileField))) {
            $parts[] = 'operate: false';
        }
        if ($formatter === 'datetime' || in_array($column['DATA_TYPE'], ['date', 'datetime', 'timestamp'], true)) {
            $parts[] = "searchType: 'time'";
            $formatter = 'datetime';
        }
        if ($this->matchSuffix($field, $this->selectpageSuffix)) {
            $parts[] = "searchType: 'remoteSelect'";
        }
        if ($formatter) {
            $parts[] = 'templet: bdTable.api.formatter.' . $formatter;
        }
        if ($inputType && in_array($inputType, ['select', 'checkbox', 'radio'], true)) {
            $parts[0] = "field: \"{$field}_text\"";
        }
        return '                    { ' . implode(', ', $parts) . ' }';
    }

    protected function fieldType(array $column): string
    {
        $type = match ($column['DATA_TYPE']) {
            'bigint', 'int', 'mediumint', 'smallint', 'tinyint', 'decimal', 'double', 'float' => 'number',
            'enum', 'set' => 'select',
            'longtext', 'text', 'mediumtext', 'tinytext' => 'textarea',
            'year', 'date', 'time', 'datetime', 'timestamp' => 'datetime',
            default => 'text',
        };
        $field = $column['COLUMN_NAME'];
        if ($this->matchSuffix($field, $this->intDateSuffix)) {
            $type = 'datetime';
        }
        if ($this->matchSuffix($field, $this->enumRadioSuffix) && $column['DATA_TYPE'] === 'enum') {
            $type = 'radio';
        }
        if ($this->matchSuffix($field, $this->setCheckboxSuffix) && $column['DATA_TYPE'] === 'set') {
            $type = 'checkbox';
        }
        if ($this->matchSuffix($field, $this->switchSuffix) && in_array($column['COLUMN_TYPE'], ['tinyint(1)', 'char(1)'], true)) {
            $type = 'switch';
        }
        return $type;
    }

    protected function items(array $column): array
    {
        $comment = str_replace('，', ',', (string)($column['COLUMN_COMMENT'] ?? ''));
        $items = [];
        if (stripos($comment, ':') !== false && stripos($comment, '=') !== false) {
            [, $item] = explode(':', $comment, 2);
            foreach (explode(',', $item) as $pair) {
                $val = explode('=', $pair, 2);
                if (count($val) === 2) {
                    $items[trim($val[0])] = $column['COLUMN_NAME'] . ' ' . trim($val[0]);
                }
            }
            return $items;
        }
        if (in_array($column['DATA_TYPE'], ['enum', 'set'], true)) {
            $raw = substr($column['COLUMN_TYPE'], strlen($column['DATA_TYPE']) + 1, -1);
            foreach (explode(',', str_replace("'", '', $raw)) as $value) {
                $items[$value] = is_numeric($value) ? $column['COLUMN_NAME'] . ' ' . $value : $value;
            }
        }
        return $items;
    }

    protected function enumMethods(&$getEnum, &$assign, $field, array $itemArr, string $inputType): void
    {
        $list = $this->listName($field);
        $method = 'get' . ucfirst($list);
        $pairs = [];
        foreach ($itemArr as $key => $value) {
            $pairs[] = "'" . str_replace("'", "\\'", (string)$key) . "' => __('" . $this->langKey((string)$value) . "')";
        }
        $getEnum[] = "    public function {$method}()\n    {\n        return [" . implode(', ', $pairs) . "];\n    }";
        $assign[] = "        \$this->view->assign('{$list}', \$this->model->{$method}());";
        unset($inputType);
    }

    protected function attrMethods(&$getAttr, &$setAttr, &$append, $field, string $inputType): void
    {
        $attr = ucfirst($this->camel($field));
        $list = 'get' . ucfirst($this->listName($field));
        $stub = in_array($inputType, ['checkbox', 'select'], true) && $inputType === 'checkbox' ? 'checkbox' : ($inputType === 'radio' ? 'radio' : 'select');
        if ($inputType === 'checkbox') {
            $stub = 'checkbox';
        }
        $getAttr[] = $this->stub('mixins/' . $stub, ['field' => $field, 'methodName' => "get{$attr}TextAttr", 'listMethodName' => $list]);
        if (in_array($inputType, ['checkbox', 'select'], true)) {
            $setAttr[] = "    protected function set{$attr}Attr(\$value)\n    {\n        return is_array(\$value) ? implode(',', \$value) : \$value;\n    }";
        }
        $append[] = "        '{$field}_text'";
    }

    protected function formGroup(string $field, string $content): string
    {
        $lang = $this->langKey($field);
        return "    <div class=\"layui-form-item\">\n        <label class=\"layui-form-label\">{:__('{$lang}')}</label>\n        <div class=\"layui-input-block\">\n            {$content}\n        </div>\n    </div>";
    }

    protected function langItem(string $field, string $content): string
    {
        $content = str_replace('，', ',', $content);
        $items = [];
        if (stripos($content, ':') !== false && stripos($content, '=') !== false) {
            [$title, $item] = explode(':', $content, 2);
            $items[$this->langKey($field)] = trim($title);
            foreach (explode(',', $item) as $pair) {
                $val = explode('=', $pair, 2);
                if (count($val) === 2) {
                    $items[$this->langKey($field . ' ' . trim($val[0]))] = trim($val[1]);
                }
            }
        } else {
            $items[$this->langKey($field)] = $content;
        }
        $lines = [];
        foreach ($items as $key => $value) {
            $this->fieldMaxLen = max($this->fieldMaxLen, strlen($key));
            $lines[] = "    '{$key}' => '" . str_replace("'", "\\'", $value) . "'";
        }
        return implode(",\n", $lines);
    }

    protected function write(string $name, array $data, string $pathname): void
    {
        $dir = dirname($pathname);
        if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new \RuntimeException('无法创建目录：' . $dir);
        }
        file_put_contents($pathname, $this->stub($name, $data));
    }

    protected function stub(string $name, array $data): string
    {
        $file = __DIR__ . '/Crud/stubs/' . $name . '.stub';
        if (!isset($this->stubList[$file])) {
            $this->stubList[$file] = file_get_contents($file);
        }
        $search = $replace = [];
        foreach ($data as $key => $value) {
            $search[] = '{%' . $key . '%}';
            $replace[] = is_array($value) ? '' : (string)$value;
        }
        return str_replace($search, $replace, $this->stubList[$file]);
    }

    protected function parseName(string $type, ?string $name, string $table, string $module): array
    {
        $name = $name ? str_replace(['.', '\\'], '/', $name) : str_replace('_', '/', $table);
        $arr = explode('/', trim($name, '/'));
        $class = ucfirst(array_pop($arr));
        if (in_array(strtolower($class), $this->internalKeywords, true)) {
            throw new \InvalidArgumentException('Unable to use internal variable:' . $class);
        }
        $namespace = 'app\\' . $module . '\\' . $type . ($arr ? '\\' . implode('\\', $arr) : '');
        $file = root_path() . 'app/' . $module . '/' . $type . '/' . ($arr ? implode('/', $arr) . '/' : '') . $class . '.php';
        return [$namespace, $class, $file, array_merge($arr, [$class])];
    }

    protected function detectTimeFields(array $fields): void
    {
        foreach (['create_time' => 'createtime', 'update_time' => 'updatetime', 'delete_time' => 'deletetime'] as $modern => $legacy) {
            $prop = match ($modern) {
                'create_time' => 'createTimeField',
                'update_time' => 'updateTimeField',
                default => 'deleteTimeField',
            };
            if (!in_array($modern, $fields, true) && in_array($legacy, $fields, true)) {
                $this->{$prop} = $legacy;
            }
        }
    }

    /**
     * bigint 等整数时间字段按时间戳读写
     */
    protected function modelTypeList(array $columnList): string
    {
        $lines = [];
        foreach ($columnList as $column) {
            if (in_array($column['COLUMN_NAME'], [$this->createTimeField, $this->updateTimeField, $this->deleteTimeField], true)
                && in_array($column['DATA_TYPE'], ['int', 'bigint', 'mediumint', 'smallint', 'tinyint'], true)) {
                $lines[] = "        '{$column['COLUMN_NAME']}' => 'int',";
            }
        }
        return implode("\n", $lines);
    }

    protected function tableComment(string $fullTable): string
    {
        $config = TableManager::getConnectionConfig();
        $row = Db::query('SELECT TABLE_COMMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?', [$config['database'], $fullTable]);
        $comment = $row[0]['TABLE_COMMENT'] ?? '';
        return $comment !== '' ? $comment : $fullTable;
    }

    protected function prefix(): string
    {
        return (string)config('database.connections.' . config('database.default') . '.prefix');
    }

    protected function truthy($value): bool
    {
        return !in_array($value, [null, false, '', '0', 'false', 'no'], true);
    }

    protected function matchSuffix(string $field, $suffix): bool
    {
        foreach ((array)$suffix as $item) {
            if (preg_match('/' . preg_quote($item, '/') . '$/i', $field)) {
                return true;
            }
        }
        return false;
    }

    protected function listName(string $field): string
    {
        return $this->camel($field) . 'List';
    }

    protected function camel(string $value): string
    {
        return str_replace(' ', '', ucwords(str_replace('_', ' ', $value)));
    }

    protected function langKey(string $field): string
    {
        return str_replace(' ', '', ucwords(str_replace(['_', '.'], ' ', $field)));
    }
}
