<?php

namespace app\admin\controller\Auth;

use app\admin\model\AdminRule;
use app\common\controller\Backend;

class Rule extends Backend
{
    protected $rulelist = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        if (!$this->auth->isSuperAdmin()) {
            $this->error(__('Access is allowed only to the super management group'));
        }
        $this->model=new AdminRule();

    }


    /**
     * 查看
     */
    public function index()
    {
        if ($this->request->isAjax()) {
            $list = $this->rulelist;
            $total = count($this->rulelist);
            $result = array("total" => $total, "rows" => $list);

            return json($result);
        }
        return $this->view->fetch();
    }
}